### ISSUE TITLE
owntracks node causes node-red 13.4 to not deploy

### ISSUE THREAD

**Issue by rlust** [hardillb/node-red-contrib-owntracks#1]
When I add this node it causes node-red to stop sending any messages to the debug list.
I am using the .2 version of the node.

**Comment by hardillb** [comment]
Your going to have supply WAY more information before anybody can even start to help and what you have supplied seams to be contradictory.
1. Some indication of how you've wired it up (a screen shot of the flow or a copy of the actual flow file).
2. A copy of the console output from when you've tried to deploy so we can see any error messages.
3. Does it deploy or not? It won't deploy if you've not set a shared secret in the config.
4. How did you deploy the node, with npm or from the git src

**Comment by hardillb** [comment]
It's been over a month and no response, I'm closing this
